X=MsgBox("INSTALL NVIDA DRIVE INFORMTION KILL 7%",4+16,"Virus NVIDIA 7%")

X=MsgBox("INSTALL NVIDA DRIVE INFORMTION KILL 20%",4+16,"Virus NVIDIA 20%")

X=MsgBox("INSTALL NVIDA DRIVE INFORMTION KILL 45%",4+16,"Virus NVIDIA 45%")

X=MsgBox("INSTALL NVIDA DRIVE INFORMTION KILL 80%",4+16,"Virus NVIDIA 80%")

X=MsgBox("INSTALL NVIDA DRIVE INFORMTION KILL 87%",4+16,"Virus NVIDIA 87%")

X=MsgBox("INSTALL NVIDA DRIVE INFORMTION KILL 99%",4+16,"Virus NVIDIA 99%")

X=MsgBox("NVIDA DRIVE INFORMTION KILL WAS SUCCESFULL DOWNLADED",4+16,"Virus NVIDIA")